### PR TITLE
Refactor copypasta

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by ScarylePoo** [comment]
I'm hesitant with this because the defs are designed to be overridden by games or maps. In doing this, it makes the reference def a bit more arduous than simply copy and pasting. Although, to some degree it might not matter. Thoughts?

**Comment by ScarylePoo** [comment]
Lel, who am I kidding, most people refuse to use helpful tools anyway, so what do I care?

**Comment by sprunk** [comment]
When the defs are grouped it's still just a matter of copying the file to override them. Grouping makes sure that changes a developer makes to similar defs are consistent.

**Comment by ScarylePoo** [comment]
Yeah I know, I'm just trying to make it as easy as possible for less knowledgeable people. That said, getting people to adopt it seems to be extraordinarily difficult for some odd reason. You would think that people would want mappers to make their maps visually interesting.

**Pull request merged**
